plugins {
	id 'java-library'
	id 'maven-publish'
}

version = project.version
group = project.maven_group

repositories {
	mavenCentral()
	maven {
		name = "Minecraft Libraries"
		url = "https://libraries.minecraft.net"
	}
}

dependencies {
	api "com.mojang:datafixerupper:${project.dfu_version}"
	api "org.jspecify:jspecify:${project.jspecify_version}"

	testImplementation(platform('org.junit:junit-bom:5.10.3'))
	testImplementation('org.junit.jupiter:junit-jupiter')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

base {
	archivesName = project.archives_base_name
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

test {
	useJUnitPlatform()
}

jar {
	def archivesName = project.base.archivesName
	inputs.property "archivesName", archivesName.get()

	from("LICENSE") {
		rename { "${it}_${archivesName.get()}" }
	}
}

// Configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			groupId = "net.azureaaron"
			artifactId = "legacy-item-dfu"
			
			from components.java
		}
	}

	repositories {
		maven {
			url = "https://maven.azureaaron.net/releases"

			credentials(PasswordCredentials) {
				username = System.getenv("AARON_MAVEN_USER");
				password = System.getenv("AARON_MAVEN_PASS");
			}
		}
	}
}
def portRepository = providers.gradleProperty('portMavenRepository')
if (portRepository.isPresent()) {
    publishing {
        repositories {
            maven { name = 'portWorkspace'; url = uri(portRepository.get()) }
        }
    }
}
