# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.country=CA -Duser.language=en
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Library Properties
	version = 1.0.4+26.2
	maven_group = net.azureaaron
	archives_base_name = legacy-item-dfu

# Dependencies
	dfu_version = 10.0.21
	jspecify_version = 1.0.0